Add improved docs
johno/remark-unwrap-images pull request #7
Opened 2021-11-03 18:21 UTC by wooorm

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

[View rendered](https://github.com/remarkjs/remark-unwrap-images/blob/docs/readme.md)

Related-to: unifiedjs/unified#168.

/cc @nemo-omen @remcohaszing @ChristianMurphy @Murderlon @with-heart @joostdecock @mgan59

2021-11-03 18:22 UTC, wooorm reviewed
✅

2021-11-03 21:16 UTC, remcohaszing requested changes

2021-11-03 21:16 UTC, remcohaszing commented on readme.md
> +displaying them at the full available with, because paragraph styles no longer
I think you meant _width_.

```suggestion
displaying them at the full available width, because paragraph styles no longer
```

2021-11-04 09:57 UTC, remcohaszing approved these changes

2021-11-04 12:49 UTC, with-heart approved these changes

2021-11-04 15:02 UTC, ChristianMurphy approved these changes

2021-11-05 14:06 UTC, merged